name: Trivy vulnerability scanner

on:
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review]
    branches:
      - main
  push:
    branches:
      - main

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  build-and-scan:
    name: Trivy vulnerability scanner
    if: ${{ !github.event.pull_request.draft }}
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.2

      - name: Build an image from Dockerfile
        run: yarn docker-build

      - name: Run Trivy vulnerability scanner
        uses: aquasecurity/trivy-action@0.14.0
        with:
          image-ref: ${{ github.event.repository.name }}
          exit-code: '1'
          ignore-unfixed: true
          severity: 'CRITICAL,HIGH'
